[tool.poetry]
name = "data-adapter"
version = "0.1.0"
description = "Data ingestion adapter for financial data APIs"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.27.0"
redis = {extras = ["hiredis"], version = "^5.0.4"}
pydantic = "^2.7.1"
pydantic-settings = "^2.2.1"
asyncpg = "^0.30.0"
databases = "^0.9.0"
sqlalchemy = "^2.0.41"
psycopg2-binary = "^2.9.10"
greenlet = "^3.2.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"
respx = "^0.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 