[tool.poetry]
name = "api-gateway"
version = "0.1.0"
description = "API Gateway for FinAnalyzer"
authors = ["Milan Amsterdam <milan@amsterdam.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.13"
uvicorn = {extras = ["standard"], version = "^0.34.3"}
pydantic = "^2.11.7"
python-dotenv = "^1.1.0"
pydantic-settings = "^2.2.1"
httpx = "^0.28.1"
redis = {extras = ["hiredis"], version = "^5.0.4"}
asyncpg = "^0.30.0"
databases = "^0.9.0"
sqlalchemy = "^2.0.41"
psycopg2-binary = "^2.9.10"
greenlet = "^3.2.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]

