name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify project structure
        run: |
          echo "Checking project structure..."
          ls -la
          echo "Checking workspace config..."
          cat pnpm-workspace.yaml
          echo "Checking package.json..."
          cat package.json

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
